branch-defaults:
  default:
    environment: taggit-ui-dev
global:
  application_name: taggit-ui
  branch: null
  default_ec2_keyname: personal ec2 access key pair
  default_platform: Docker 18.09.9-ce
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
